# Generates CSS stub files for Kiso's palette files in the host app.
#
# tailwindcss-rails creates a stub at app/assets/builds/tailwind/kiso.css
# for engine.css, but it doesn't handle subdirectories. Palette files at
# app/assets/tailwind/kiso/palettes/*.css inside the gem are invisible to
# the host app's Tailwind CLI without stubs.
#
# This task creates matching stubs so host apps can import palettes with:
#   @import "../builds/tailwind/kiso/palettes/blue.css";

namespace :kiso do
  desc "Generate CSS stubs for Kiso palette files"
  task palettes: :environment do
    palette_dir = Kiso::Engine.root.join("app/assets/tailwind/kiso/palettes")
    next unless palette_dir.directory?

    output_dir = Rails.root.join("app/assets/builds/tailwind/kiso/palettes")
    FileUtils.mkdir_p(output_dir)

    Dir[palette_dir.join("*.css")].each do |source|
      name = File.basename(source)
      stub_path = output_dir.join(name)
      File.write(stub_path, <<~CSS)
        /* DO NOT MODIFY THIS FILE, it was auto-generated by kiso */

        @import "#{source}";
      CSS
    end
  end
end

# Hook into tailwindcss-rails build pipeline so palette stubs are
# generated before the Tailwind CLI runs.
if Rake::Task.task_defined?("tailwindcss:engines")
  Rake::Task["tailwindcss:engines"].enhance(["kiso:palettes"])
end
