# frozen_string_literal: true

namespace :kiso do
  namespace :tailwindcss do
    desc "Generate Kiso engine CSS with @source directives for Tailwind v4"
    task generate_sources: :environment do
      require "fileutils"

      engine_root = Kiso::Engine.root
      output_dir = Rails.root.join("app/assets/builds/tailwind")
      output_file = output_dir.join("kiso.css")

      source_paths = [
        engine_root.join("app/views"),
        engine_root.join("app/helpers"),
        engine_root.join("lib/kiso/themes")
      ]

      lines = ["/* DO NOT MODIFY — auto-generated by kiso:tailwindcss:generate_sources */", ""]
      lines << %(@import "#{engine_root.join("app/assets/tailwind/kiso/engine.css")}";)
      lines << ""
      source_paths.each { |p| lines << %(@source "#{p}";) if p.exist? }
      lines << ""
      content = lines.join("\n")

      FileUtils.mkdir_p(output_dir)
      unless output_file.exist? && output_file.read == content
        output_file.write(content)
      end
    end
  end
end

if Rake::Task.task_defined?("tailwindcss:build")
  Rake::Task["tailwindcss:build"].enhance(["kiso:tailwindcss:generate_sources"])
end

if Rake::Task.task_defined?("tailwindcss:watch")
  Rake::Task["tailwindcss:watch"].enhance(["kiso:tailwindcss:generate_sources"])
end
