module Kiso
  # Rails engine that integrates Kiso into host applications.
  #
  # Registers initializers for:
  # - ClassVariants merger (TailwindMerge for class deduplication)
  # - Global theme overrides ({ThemeOverrides})
  # - View helpers ({ComponentHelper}, {IconHelper})
  # - Importmap and asset pipeline paths
  # - Lookbook preview path registration
  class Engine < ::Rails::Engine
    isolate_namespace Kiso

    # Configures ClassVariants to use TailwindMerge for class deduplication.
    # This ensures conflicting Tailwind utilities are resolved correctly
    # when merging base, variant, and override classes.
    initializer "kiso.class_variants" do
      ClassVariants.configure do |config|
        merger = TailwindMerge::Merger.new
        config.process_classes_with { |classes| merger.merge(classes) }
      end
    end

    # Applies global theme overrides from {Configuration#theme} to
    # theme constants. Runs after app initializers so the host app's
    # +config/initializers/kiso.rb+ has populated +config.theme+.
    initializer "kiso.theme_overrides", after: :load_config_initializers do
      Kiso::ThemeOverrides.apply!
    end

    # Makes {ComponentHelper}, {AppComponentHelper}, and {IconHelper} available in all views.
    initializer "kiso.helpers" do
      ActiveSupport.on_load(:action_view) do
        include Kiso::UiContextHelper
        include Kiso::ComponentHelper
        include Kiso::AppComponentHelper
        include Kiso::IconHelper
        include Kiso::ThemeHelper
      end
    end

    # Appends Kiso's importmap config and JavaScript assets for importmap-rails apps.
    initializer "kiso.importmap", before: "importmap" do |app|
      if app.config.respond_to?(:importmap)
        app.config.importmap.paths << root.join("config/importmap.rb")
        app.config.importmap.cache_sweepers << root.join("app/javascript")
      end
    end

    # Appends Kiso's JavaScript directory to the asset pipeline (Propshaft/Sprockets).
    initializer "kiso.assets" do |app|
      if app.config.respond_to?(:assets)
        app.config.assets.paths << root.join("app/javascript")
      end
    end

    # Filters tailwindcss-rails engine CSS stubs from Propshaft's :app stylesheet
    # resolution so they are never served to the browser.
    #
    # Background: tailwindcss-rails generates intermediate stub files in the host
    # app at app/assets/builds/tailwind/<engine_name>.css. Each stub contains a
    # single @import with an absolute filesystem path:
    #
    #   @import "/path/to/gems/kiso-0.2.0/app/assets/tailwind/kiso/engine.css";
    #
    # The Tailwind CLI resolves this @import at build time and inlines the engine
    # CSS into the compiled output (app/assets/builds/tailwind.css). The stubs are
    # build-time intermediates — they should never reach the browser.
    #
    # The problem: Propshaft's stylesheet_link_tag :app (the Rails 8.1 default)
    # globs app/assets/**/*.css and generates a <link> tag for every match. This
    # picks up the stubs alongside the compiled tailwind.css. The browser then
    # receives a stub, encounters the @import with a filesystem path, interprets
    # it as a URL, and gets a 404.
    #
    # Propshaft's excluded_paths config only removes top-level directories from
    # the load path — it can't exclude files within a load path directory. The
    # stubs live inside app/assets/builds/ (a single load path entry), so
    # excluded_paths can't help.
    #
    # This fix prepends a filter onto Propshaft::Helper#app_stylesheets_paths to
    # reject any asset whose logical path starts with "tailwind/" — these are
    # always engine stubs generated by tailwindcss-rails, never user CSS.
    # The compiled output is "tailwind.css" (no slash), so it passes through.
    #
    # This affects ALL engine stubs, not just Kiso's, because the problem is
    # systemic to how tailwindcss-rails engine bundling interacts with Propshaft's
    # :app resolution.
    #
    # See: propshaft-1.3.1 lib/propshaft/helper.rb#app_stylesheets_paths
    # See: tailwindcss-rails lib/tailwindcss/engines.rb (stub generation)
    # See: tailwindcss-rails lib/tailwindcss/engine.rb (excludes app/assets/tailwind
    #      but not app/assets/builds/tailwind)
    initializer "kiso.filter_tailwind_stubs" do
      ActiveSupport.on_load(:action_view) do
        if defined?(Propshaft::Helper)
          Propshaft::Helper.prepend(Kiso::PropshaftTailwindStubFilter)
        end
      end
    end

    # Watches lib/kiso/themes/ in development and reloads changed theme
    # constants so you don't have to restart the server after every tweak.
    # Uses Rails' built-in FileUpdateChecker (same mechanism as route reloading).
    initializer "kiso.theme_reloading" do |app|
      if Rails.env.development? || Rails.env.test?
        theme_dir = root.join("lib/kiso/themes")
        theme_files = Dir[theme_dir.join("*.rb")]

        reloader = app.config.file_watcher.new(theme_files) do
          # Suppress "already initialized constant" warnings during reload.
          # Theme files assign to constants (Badge = ClassVariants.build(...))
          # which is intentional — we want to replace the old instance.
          verbose, $VERBOSE = $VERBOSE, nil
          begin
            theme_files.each { |file| load file }
          ensure
            $VERBOSE = verbose
          end
          Kiso::ThemeOverrides.reset!
          Kiso::ThemeOverrides.apply!
        end

        app.reloaders << reloader

        ActiveSupport::Reloader.to_prepare do
          reloader.execute_if_updated
        end
      end
    end

    # Adds +app/themes/+ to the host app's autoload paths so theme constants
    # like +AppThemes::PricingCard+ resolve automatically. Only added when
    # the directory exists.
    initializer "kiso.app_themes" do |app|
      themes_path = app.root.join("app/themes")
      if themes_path.directory?
        app.config.autoload_paths << themes_path.to_s
      end
    end

    # Watches +app/themes/+ in the host app and reloads changed theme
    # constants in development. Uses directory-based watching so new files
    # added after boot are picked up automatically.
    initializer "kiso.app_theme_reloading" do |app|
      if Rails.env.development? || Rails.env.test?
        themes_path = app.root.join("app/themes")
        if themes_path.directory?
          reloader = app.config.file_watcher.new([], {themes_path.to_s => ["rb"]}) do
            # Re-glob to pick up new files added after boot
            verbose, $VERBOSE = $VERBOSE, nil
            begin
              Dir[themes_path.join("**/*.rb")].each { |file| load file }
            ensure
              $VERBOSE = verbose
            end
          end

          app.reloaders << reloader

          ActiveSupport::Reloader.to_prepare do
            reloader.execute_if_updated
          end
        end
      end
    end

    # Registers Kiso's component previews with Lookbook when available.
    initializer "kiso.lookbook", after: :load_config_initializers do
      if defined?(Lookbook)
        Lookbook.config.preview_paths << root.join("test/components/previews").to_s
      end
    end
  end
end
