module Kiso
  # Rails engine that integrates Kiso into host applications.
  #
  # Registers initializers for:
  # - ClassVariants merger (TailwindMerge for class deduplication)
  # - Global theme overrides ({ThemeOverrides})
  # - View helpers ({ComponentHelper}, {IconHelper})
  # - Importmap and asset pipeline paths
  # - Lookbook preview path registration
  class Engine < ::Rails::Engine
    isolate_namespace Kiso

    # Loads Kiso's locale files so host apps can override translations.
    initializer "kiso.i18n" do
      config.i18n.load_path += Dir[root.join("config/locales/**/*.yml")]
    end

    # Configures ClassVariants to use TailwindMerge for class deduplication.
    # This ensures conflicting Tailwind utilities are resolved correctly
    # when merging base, variant, and override classes.
    initializer "kiso.class_variants" do
      ClassVariants.configure do |config|
        merger = TailwindMerge::Merger.new
        config.process_classes_with { |classes| merger.merge(classes) }
      end
    end

    # Applies global theme overrides from {Configuration#theme} to
    # theme constants. Runs after app initializers so the host app's
    # +config/initializers/kiso.rb+ has populated +config.theme+.
    initializer "kiso.theme_overrides", after: :load_config_initializers do
      Kiso::ThemeOverrides.apply!
    end

    # Makes {ComponentHelper}, {AppComponentHelper}, and {IconHelper} available in all views.
    initializer "kiso.helpers" do
      ActiveSupport.on_load(:action_view) do
        include Kiso::UiContextHelper
        include Kiso::ComponentHelper
        include Kiso::AppComponentHelper
        include Kiso::IconHelper
        include Kiso::ThemeHelper
      end
    end

    # Appends Kiso's importmap config and JavaScript assets for importmap-rails apps.
    initializer "kiso.importmap", before: "importmap" do |app|
      if app.config.respond_to?(:importmap)
        app.config.importmap.paths << root.join("config/importmap.rb")
        app.config.importmap.cache_sweepers << root.join("app/javascript")
      end
    end

    # Appends Kiso's JavaScript directory to the asset pipeline (Propshaft/Sprockets).
    initializer "kiso.assets" do |app|
      if app.config.respond_to?(:assets)
        app.config.assets.paths << root.join("app/javascript")
      end
    end

    # Filters tailwindcss-rails engine CSS stubs from Propshaft's :app stylesheet
    # resolution so they are never served to the browser.
    #
    # Background: tailwindcss-rails generates intermediate stub files in the host
    # app at app/assets/builds/tailwind/<engine_name>.css. Each stub contains a
    # single @import with an absolute filesystem path:
    #
    #   @import "/path/to/gems/kiso-0.2.0/app/assets/tailwind/kiso/engine.css";
    #
    # The Tailwind CLI resolves this @import at build time and inlines the engine
    # CSS into the compiled output (app/assets/builds/tailwind.css). The stubs are
    # build-time intermediates — they should never reach the browser.
    #
    # The problem: Propshaft's stylesheet_link_tag :app (the Rails 8.1 default)
    # globs app/assets/**/*.css and generates a <link> tag for every match. This
    # picks up the stubs alongside the compiled tailwind.css. The browser then
    # receives a stub, encounters the @import with a filesystem path, interprets
    # it as a URL, and gets a 404.
    #
    # Propshaft's excluded_paths config only removes top-level directories from
    # the load path — it can't exclude files within a load path directory. The
    # stubs live inside app/assets/builds/ (a single load path entry), so
    # excluded_paths can't help.
    #
    # This fix prepends a filter onto Propshaft::Helper#app_stylesheets_paths to
    # reject any asset whose logical path starts with "tailwind/" — these are
    # always engine stubs generated by tailwindcss-rails, never user CSS.
    # The compiled output is "tailwind.css" (no slash), so it passes through.
    #
    # This affects ALL engine stubs, not just Kiso's, because the problem is
    # systemic to how tailwindcss-rails engine bundling interacts with Propshaft's
    # :app resolution.
    #
    # See: propshaft-1.3.1 lib/propshaft/helper.rb#app_stylesheets_paths
    # See: tailwindcss-rails lib/tailwindcss/engines.rb (stub generation)
    # See: tailwindcss-rails lib/tailwindcss/engine.rb (excludes app/assets/tailwind
    #      but not app/assets/builds/tailwind)
    initializer "kiso.filter_tailwind_stubs" do
      ActiveSupport.on_load(:action_view) do
        if defined?(Propshaft::Helper)
          Propshaft::Helper.prepend(Kiso::PropshaftTailwindStubFilter)
        end
      end
    end

    # Watches lib/kiso/themes/ in development and reloads changed theme
    # constants so you don't have to restart the server after every tweak.
    # Uses Rails' built-in FileUpdateChecker (same mechanism as route reloading).
    initializer "kiso.theme_reloading" do |app|
      if Rails.env.development? || Rails.env.test?
        theme_dir = root.join("lib/kiso/themes")
        theme_files = Dir[theme_dir.join("*.rb")]

        reloader = app.config.file_watcher.new(theme_files) do
          # Suppress "already initialized constant" warnings during reload.
          # Theme files assign to constants (Badge = ClassVariants.build(...))
          # which is intentional — we want to replace the old instance.
          verbose, $VERBOSE = $VERBOSE, nil
          begin
            theme_files.each { |file| load file }
          ensure
            $VERBOSE = verbose
          end
          Kiso::ThemeOverrides.reset!
          Kiso::ThemeOverrides.apply!
        end

        app.reloaders << reloader

        ActiveSupport::Reloader.to_prepare do
          reloader.execute_if_updated
        end
      end
    end

    # Loads the active app theme from +app/themes/<name>/+.
    #
    # Theme files define constants under the +AppThemes::+ namespace
    # (e.g. +AppThemes::StatusBadge+) and are loaded via +require+ at
    # boot. The active theme is determined by {Configuration#app_theme}
    # (defaults to +:default+).
    #
    # No-op when +app/themes/+ doesn't exist. Raises a helpful error
    # when the configured theme directory is missing.
    initializer "kiso.app_themes", after: :load_config_initializers do |app|
      themes_root = app.root.join("app/themes")
      next unless themes_root.directory?

      theme_name = Kiso.config.app_theme
      active_path = themes_root.join(theme_name.to_s)

      unless active_path.directory?
        available = Dir.children(themes_root.to_s)
          .select { |d| File.directory?(themes_root.join(d)) }
          .sort

        msg = "Kiso app theme :#{theme_name} not found. " \
              "Expected directory: #{active_path}"
        msg += if available.any?
          "\nAvailable themes: #{available.map { |d| ":#{d}" }.join(", ")}"
        else
          "\nNo theme directories found in #{themes_root}. " \
          "Run: bin/rails generate kiso:app_component your_component"
        end
        raise Kiso::Error, msg
      end

      Object.const_set(:AppThemes, Module.new) unless Object.const_defined?(:AppThemes)

      Dir[active_path.join("**/*.rb")].sort.each { |file| require file }
    end

    # Watches the active app theme directory in development and reloads
    # changed theme constants. Uses directory-based watching so new files
    # added after boot are picked up automatically.
    initializer "kiso.app_theme_reloading" do |app|
      next unless Rails.env.development? || Rails.env.test?

      themes_root = app.root.join("app/themes")
      next unless themes_root.directory?

      active_path = themes_root.join(Kiso.config.app_theme.to_s)
      next unless active_path.directory?

      reloader = app.config.file_watcher.new([], {active_path.to_s => ["rb"]}) do
        verbose, $VERBOSE = $VERBOSE, nil
        begin
          Dir[active_path.join("**/*.rb")].sort.each { |file| load file }
        ensure
          $VERBOSE = verbose
        end
      end

      app.reloaders << reloader

      ActiveSupport::Reloader.to_prepare do
        reloader.execute_if_updated
      end
    end

    # Registers Kiso's component previews with Lookbook when available.
    initializer "kiso.lookbook", after: :load_config_initializers do
      if defined?(Lookbook)
        Lookbook.config.preview_paths << root.join("test/components/previews").to_s
      end
    end
  end
end
