service: kiso-lookbook
image: steveclarke/kiso-lookbook

servers:
  web:
    hosts:
      - <%= ENV["DEPLOY_HOST"] %>

proxy:
  ssl: true
  host: lookbook.kisoui.com
  app_port: 3000

registry:
  server: localhost:5555

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY

builder:
  arch: amd64

ssh:
  user: deploy

aliases:
  console: app exec --interactive --reuse "cd lookbook && bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
